name: Storefront 1000033924
on:
  push:
    branches: [main]
env:
  DEPLOY_ENV: production    # 默认部署环境
  
permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy to Oxygen
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true
          
      - name: Install pnpm
        run: npm install -g pnpm@8
        
      - name: Cache pnpm modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build project
        run: |
          pnpm install
          pnpm build
        env:
          NODE_ENV: production  # 强制生产模式

      - name: Install Shopify CLI
        env:
          PNPM_HOME: /usr/local/bin  # 指定全局安装路径
        run: |
          npm uninstall -g @shopify/cli @shopify/cli-hydrogen
          npm install -g @shopify/cli@latest @shopify/cli-hydrogen@latest
          shopify version
            
      - name: Build and Publish to Oxygen
        run: npx shopify hydrogen deploy --verbose --env production --path dist
        env:
          SHOPIFY_HYDROGEN_DEPLOYMENT_TOKEN: ${{ secrets.OXYGEN_DEPLOYMENT_TOKEN_1000033924 }}
